### ISSUE TITLE
Segmentation fault with slurm 23.02

### ISSUE THREAD

**Issue by pnsinha** [mercanca/spart#17]
```
./spart
Segmentation fault (core dumped)
```
During the compilation with slurm 23.02, I received following warning: 
```
gcc -lslurm spart.c -o spart -I/software/slurm-current-el7-x86_64/include -L/software/slurm-current-el7-x86_64/lib
spart.c: In function 'main':
spart.c:411:24: warning: implicit declaration of function 'slurmdb_qos_str'; did you mean 'slurmdb_qos_get'? [-Wimplicit-function-declaration]
  411 |         qos2 = (char *)slurmdb_qos_str(qosn_list, atoi(qos));
      |                        ^~~~~~~~~~~~~~~
      |                        slurmdb_qos_get
spart.c:411:16: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
  411 |         qos2 = (char *)slurmdb_qos_str(qosn_list, atoi(qos));
```

**Comment by mercanca** [comment]
To understand, which line give this core dumped error, Would you compile with -g:
gcc -lslurm spart.c -o spart -I/software/slurm-current-el7-x86_64/include -L/software/slurm-current-el7-x86_64/lib -g

Than run again. if it gives "core dumped" again, please run with gdb like this:
gdb ./spart

after gdb start, type:
run
when core dump happened:
bt
and please post outputs.

**Comment by pnsinha** [comment]
Sorry for the delay. Here is the output of gdb.
```
gdb ./spart
GNU gdb (GDB) Red Hat Enterprise Linux 7.6.1-120.el7
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from /home/pnsinha/github/spart/spart...done.
(gdb) run
Starting program: /home/pnsinha/github/spart/./spart 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7b3658f in slurm_get_plugin_hash_enable (index=<optimized out>) at auth.c:163
163             return *(ops[index].hash_enable);
Missing separate debuginfos, use: debuginfo-install glibc-2.17-317.el7.x86_64 sssd-client-1.16.5-10.el7.x86_64
(gdb) bt
#0  0x00007ffff7b3658f in slurm_get_plugin_hash_enable (index=<optimized out>) at auth.c:163
#1  0x00007ffff7ab86f2 in _compute_hash (hash=0x7fffffdbe250, msg=0x7fffffdbe6c0, buffer=0x6aa420) at slurm_protocol_api.c:270
#2  slurm_buffers_pack_msg (msg=msg@entry=0x7fffffdbe6c0, buffers=buffers@entry=0x7fffffdbe3a0, block_for_forwarding=block_for_forwarding@entry=true) at slurm_protocol_api.c:1907
#3  0x00007ffff7ab8c96 in slurm_send_node_msg (fd=fd@entry=10, msg=msg@entry=0x7fffffdbe6c0) at slurm_protocol_api.c:2046
#4  0x00007ffff7ab9087 in slurm_send_recv_msg (fd=fd@entry=10, req=req@entry=0x7fffffdbe6c0, resp=resp@entry=0x7fffffdbe540, timeout=timeout@entry=0) at slurm_protocol_api.c:2344
#5  0x00007ffff7ab90b6 in _send_and_recv_msg (fd=10, req=req@entry=0x7fffffdbe6c0, resp=resp@entry=0x7fffffdbe540, timeout=timeout@entry=0) at slurm_protocol_api.c:2368
#6  0x00007ffff7aba140 in slurm_send_recv_controller_msg (request_msg=request_msg@entry=0x7fffffdbe6c0, response_msg=response_msg@entry=0x7fffffdbe540, comm_cluster_rec=0x0)
    at slurm_protocol_api.c:2485
#7  0x00007ffff7a34da3 in slurm_load_ctl_conf (update_time=0, confp=0x7fffffffd1c8) at config_info.c:1905
#8  0x0000000000404bca in main (argc=1, argv=0x7fffffffd468) at spart.c:311
```

**Comment by mercanca** [comment]
It looks like the spart can not access the slurm config. Are you run configless slurm. If so, you can solve this issue by putting a slurm config file at the server you want to run spart command.

**Comment by ysagon** [comment]
Hi, I have the same issue and we aren't running in configless mode.

**Comment by mercanca** [comment]
The some functions and data structures of the Slurm 23.02 have changed. Because of this reason, the spart can not working correctly. I am looking for a work around. But, I can not see an easy or fast solution. Sorry.

**Comment by mercanca** [comment]
I uploaded a new version of the spart command (v1.5.1). Would you try new version, the problem should be fixed.

**Comment by ysagon** [comment]
This version fixes this issue as well:) thanks

**Comment by mercanca** [comment]
It is good to know, thank you.  :-)

**Comment by pnsinha** [comment]
@mercanca, thanks for the update. It works perfectly.
