### ISSUE TITLE
Segfault in 1.0.1

### ISSUE THREAD

**Issue by kcgthb** [mercanca/spart#7]
Hello, 

We can't get `spart` 1.0.1 to run on our system, it segfaults at execution:

```
$ /usr/bin/spart
WARNING: The Slurm settings have info restrictions!
Segmentation fault
$
```

```
$ gdb /usr/bin/spart
GNU gdb (GDB) Red Hat Enterprise Linux 7.6.1-114.el7
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from /usr/bin/spart...Reading symbols from /usr/bin/spart...(no debugging symbols found)...done.
(no debugging symbols found)...done.
Missing separate debuginfos, use: debuginfo-install spart-1.0.1-1.el7.x86_64
(gdb) r
Starting program: /usr/bin/spart
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
WARNING: The Slurm settings have info restrictions!
Detaching after fork from child process 76786.

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff776ff5c in __strncmp_sse42 () from /lib64/libc.so.6
(gdb) bt
#0  0x00007ffff776ff5c in __strncmp_sse42 () from /lib64/libc.so.6
#1  0x0000000000401532 in sp_account_check ()
#2  0x0000000000404822 in main ()
```

If that's helpful, version 0.8.0 runs great on the same system.

**Comment by mercanca** [comment]
Would you recompile spart with adding -g parameter to gcc. Than, run gdb and after "segmentation fault" error, type backtrace command at gdb. It will show which line of spart code is produce this error.

**Comment by mercanca** [comment]
would you also send slurm version info with debug output.

**Comment by kcgthb** [comment]
@mercanca Sure! Here it is:

```
(gdb) bt
#0  0x00007ffff776ff5c in __strncmp_sse42 () from /lib64/libc.so.6
#1  0x0000000000401532 in sp_account_check (useracct=0x38db700, useract_count=8, partition_acct=0x7fffffffd160 "normal") at spart.c:276
#2  0x0000000000404822 in main (argc=1, argv=0x7fffffffd628) at spart.c:1242
```
and we're running Slurm 19.05.6.

Thanks!

**Comment by mercanca** [comment]
I upload a new version (1.0.2). Please check the new version.

**Comment by kcgthb** [comment]
Excellent, problem is fixed, thanks a lot!
